# Generated by Django 5.2.12 on 2026-05-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_project_creator_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project'),
        ),
    ]
