# Generated by Django 5.2.12 on 2026-05-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_id'),
        ('diyprojects', '0004_projectrating_project_projectreview_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To-Do', 'To-Do'), ('Done', 'Done')], default='Backlog', max_length=20),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diyprojects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('project', 'profile')},
        ),
    ]
