# Generated by Django 6.0.2 on 2026-05-06 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_book_available_to_borrow_book_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='date_borrowed',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
