# Generated by Django 6.0.2 on 2026-05-06 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_remove_borrow_date_borrowed_borrow_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_to_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
