# Generated by Django 6.0.2 on 2026-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_remove_commission_type_commission_commission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='people_required',
            field=models.PositiveIntegerField(),
        ),
    ]
