# Generated by Django 5.2.12 on 2026-05-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_id'),
        ('commissions', '0005_alter_commission_status_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.profile'),
        ),
    ]
