# Generated by Django 5.2.12 on 2026-05-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commissions', '0007_alter_job_commission_alter_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='open_positions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='accounts.profile'),
        ),
    ]
