# Generated by Django 6.0.2 on 2026-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_job_open_positions_alter_jobapplication_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['status', '-manpower_required', 'role']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='people_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Full'), ('2', 'Completed'), ('3', 'Discontinued')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='manpower_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Full')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('2', 'Rejected')], default='0', max_length=10),
        ),
    ]
