# Generated by Django 6.0.2 on 2026-05-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('localevents', '0004_event_event_capacity_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to='accounts.profile'),
        ),
    ]
