# Generated by Django 6.0.2 on 2026-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0005_alter_eventsignup_user_registrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='available', max_length=32),
        ),
    ]
