# Generated by Django 6.0.2 on 2026-05-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0006_alter_event_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='EventCategory',
        ),
    ]
