# Generated by Django 6.0.2 on 2026-05-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0007_rename_eventtype_eventcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCategory',
            new_name='EventType',
        ),
    ]
